"""
Report Ingestion Engine for GPU-OpenLane and ASIC physical design reports.
Parses synthesis, timing, power, physical design, and DRC metrics into structured ImplementationReport.
"""

from __future__ import annotations
from dataclasses import asdict, dataclass, field
import json
import os
from pathlib import Path
import re
from typing import Any, Dict, Optional


@dataclass
class ImplementationReport:
    """Structured physical design measurements ingested from implementation tools."""
    design: str = ""
    pdk: str = "sky130A"
    corner: str = "tt_025C_1v80"
    cell_count: int = 0
    total_area_um2: float = 0.0
    total_power_mw: float = 0.0
    dynamic_power_mw: float = 0.0
    leakage_power_mw: float = 0.0
    critical_path_ps: float = 0.0
    wns_ps: float = 0.0
    tns_ps: float = 0.0
    clock_period_ns: float = 10.0
    core_utilization: float = 0.0
    wirelength_um: float = 0.0
    drc_violations: int = 0
    timing_met: bool = True
    tool_versions: Dict[str, str] = field(default_factory=dict)
    library_assumptions: Dict[str, Any] = field(default_factory=dict)
    stage_statuses: Dict[str, str] = field(default_factory=dict)
    total_wall_time_s: float = 0.0

    @property
    def critical_path_ns(self) -> float:
        """Critical path delay in nanoseconds."""
        return self.critical_path_ps / 1000.0

    @property
    def fmax_mhz(self) -> float:
        """
        Calculated maximum achievable clock frequency based on critical path / slack.
        Fmax = 1 / (Clock Period - WNS) or 1 / Critical Path.
        """
        effective_period_ns = self.clock_period_ns - (self.wns_ps / 1000.0)
        if effective_period_ns > 0:
            return 1000.0 / effective_period_ns
        if self.critical_path_ps > 0:
            return 1000000.0 / self.critical_path_ps
        return 0.0

    def to_dict(self) -> Dict[str, Any]:
        """Convert implementation report to dictionary."""
        d = asdict(self)
        d["critical_path_ns"] = self.critical_path_ns
        d["fmax_mhz"] = self.fmax_mhz
        return d

    def to_json(self, indent: int = 2) -> str:
        """Serialize report to formatted JSON string."""
        return json.dumps(self.to_dict(), indent=indent)

    def summary(self) -> str:
        """Format a human-readable summary of physical implementation measurements."""
        lines = [
            f"Implementation Report: {self.design} ({self.pdk} @ {self.corner})",
            "-------------------------------------------------------------",
            f"  Status        : {'TIMING MET' if self.timing_met else 'TIMING VIOLATED'} | DRC: {self.drc_violations}",
            f"  Cell Count    : {self.cell_count:,} cells",
            f"  Total Area    : {self.total_area_um2:.2f} μm²",
            f"  Total Power   : {self.total_power_mw:.3f} mW (Dyn: {self.dynamic_power_mw:.3f} mW, Leak: {self.leakage_power_mw:.4f} mW)",
            f"  Critical Path : {self.critical_path_ps:.1f} ps ({self.critical_path_ns:.3f} ns)",
            f"  Clock Slack   : WNS = {self.wns_ps:.1f} ps | TNS = {self.tns_ps:.1f} ps",
            f"  Achieved Fmax : {self.fmax_mhz:.2f} MHz (Target: {1000.0/self.clock_period_ns:.2f} MHz)",
            f"  Wirelength    : {self.wirelength_um:.1f} μm | Core Util: {self.core_utilization:.1f}%",
            f"  Tool Versions : {', '.join(f'{k}: {v}' for k, v in self.tool_versions.items()) or 'N/A'}",
        ]
        return "\n".join(lines)


class ReportIngestionEngine:
    """
    Ingests output reports, JSON artifacts, and stage logs from GPU-OpenLane.
    """

    def ingest_results_json(
        self,
        json_path: str,
        manifest_path: Optional[str] = None,
    ) -> ImplementationReport:
        """
        Parse eda_results.json generated by GPU-OpenLane eda_pipeline.py.
        """
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        manifest_data = {}
        if not manifest_path:
            candidate = Path(json_path).parent / "flow_manifest.json"
            if candidate.exists():
                manifest_path = str(candidate)

        if manifest_path and os.path.exists(manifest_path):
            try:
                with open(manifest_path, "r", encoding="utf-8") as f:
                    manifest_data = json.load(f)
            except Exception:
                pass

        design_name = manifest_data.get("design", {}).get("top_module", "top")
        pdk_name = manifest_data.get("technology", {}).get("pdk", "sky130A")
        corner_name = manifest_data.get("technology", {}).get("corner", "tt_025C_1v80")
        target_period_ns = float(manifest_data.get("design", {}).get("target_clock_period_ns", 10.0))

        synth = data.get("synthesis", {})
        pnr = data.get("pnr", {})
        signoff = data.get("signoff", {})

        cell_count = int(synth.get("cells", 0))
        area_um2 = float(synth.get("area_um2", 0.0))
        crit_path_ps = float(synth.get("critical_path_ps", 0.0))

        # Timing and slack
        wns_ps = float(signoff.get("wns_ps", 0.0))
        tns_ps = float(signoff.get("tns_ps", 0.0))
        drc_violations = int(signoff.get("drc_violations", 0))

        # Power estimation
        power_mw = float(data.get("power_mw", synth.get("power_mw", 0.0)))
        dyn_power = float(data.get("dynamic_power_mw", power_mw * 0.85))
        leak_power = float(data.get("leakage_power_mw", power_mw * 0.15))

        # Physical design metrics
        wirelength_um = float(pnr.get("hpwl_um", pnr.get("wirelength_um", 0.0)))
        core_util = float(pnr.get("core_utilization", 0.0))

        # Tool versions and assumptions
        tool_versions = dict(data.get("tool_versions", {}))
        if not tool_versions:
            # Detect default tool stack
            tool_versions = {
                "synthesis": "Yosys/Synlig",
                "pnr": "OpenROAD/Metal",
                "sta": "OpenSTA",
                "drc": "KLayout",
            }

        library_assumptions = {
            "pdk": pdk_name,
            "corner": corner_name,
            "liberty_file": manifest_data.get("technology", {}).get("liberty_file", ""),
            "voltage_v": manifest_data.get("technology", {}).get("voltage", 1.8),
            "temperature_c": manifest_data.get("technology", {}).get("temperature", 25.0),
        }

        stage_statuses = {
            k: v.get("status", "unknown")
            for k, v in data.items()
            if isinstance(v, dict) and "status" in v
        }

        timing_met = (wns_ps >= 0.0)

        return ImplementationReport(
            design=design_name,
            pdk=pdk_name,
            corner=corner_name,
            cell_count=cell_count,
            total_area_um2=area_um2,
            total_power_mw=power_mw,
            dynamic_power_mw=dyn_power,
            leakage_power_mw=leak_power,
            critical_path_ps=crit_path_ps,
            wns_ps=wns_ps,
            tns_ps=tns_ps,
            clock_period_ns=target_period_ns,
            core_utilization=core_util,
            wirelength_um=wirelength_um,
            drc_violations=drc_violations,
            timing_met=timing_met,
            tool_versions=tool_versions,
            library_assumptions=library_assumptions,
            stage_statuses=stage_statuses,
            total_wall_time_s=float(data.get("_total_wall_s", 0.0)),
        )

    def ingest_directory(
        self,
        output_dir: str,
        manifest_file: Optional[str] = None,
    ) -> ImplementationReport:
        """
        Auto-discover reports from an output directory.
        """
        dir_path = Path(output_dir)
        eda_results_file = dir_path / "eda_results.json"
        discovered_manifest = manifest_file or str(dir_path / "flow_manifest.json")

        if eda_results_file.exists():
            return self.ingest_results_json(str(eda_results_file), manifest_path=discovered_manifest)

        # Fallback: scan for stage reports if eda_results.json is absent
        return self._ingest_raw_reports(dir_path, discovered_manifest)

    def _ingest_raw_reports(
        self,
        dir_path: Path,
        manifest_path: Optional[str],
    ) -> ImplementationReport:
        """Parse raw log and report files from directory."""
        report = ImplementationReport()
        if manifest_path and os.path.exists(manifest_path):
            with open(manifest_path, "r", encoding="utf-8") as f:
                man = json.load(f)
                report.design = man.get("design", {}).get("top_module", "")
                report.pdk = man.get("technology", {}).get("pdk", "sky130A")
                report.corner = man.get("technology", {}).get("corner", "tt_025C_1v80")
                report.clock_period_ns = float(man.get("design", {}).get("target_clock_period_ns", 10.0))

        # Check synthesis log / stat
        synth_stat = dir_path / "synthesis" / "stat.json"
        if synth_stat.exists():
            try:
                with open(synth_stat, "r", encoding="utf-8") as f:
                    s_data = json.load(f)
                    report.cell_count = s_data.get("num_cells", 0)
                    report.total_area_um2 = float(s_data.get("area", 0.0))
            except Exception:
                pass

        # Check OpenSTA log
        sta_log = dir_path / "signoff" / "sta.log"
        if sta_log.exists():
            try:
                with open(sta_log, "r", encoding="utf-8") as f:
                    text = f.read()
                    wns_m = re.search(r"wns\s+([-\d\.]+)", text, re.IGNORECASE)
                    if wns_m:
                        report.wns_ps = float(wns_m.group(1)) * 1000
                    crit_m = re.search(r"data arrival time\s+([-\d\.]+)", text)
                    if crit_m:
                        report.critical_path_ps = float(crit_m.group(1)) * 1000
            except Exception:
                pass

        report.timing_met = (report.wns_ps >= 0.0)
        return report
